smtp-sender v0.3.0-dev (unstable - 15/03/01)

Developer: inter6 <inter6@inter6.com>
Repository: https://github.com/inter6/smtp-sender

Release History

v0.3.0
- Support Multi-thread
- Display Send Progress Rate

v0.2.2
- Support TLS
- Improve MIME editor

v0.2.0
- Add MIME editor

v0.1.2
- Support SSL
- Support Auth - PLAIN, LOGIN, CRAM-MD5
- Support Source - EML files on directories

v0.1.0
- No auth SMTP send
- Support Source - MIME text, EML files