smtp-sender v1.2.2 (released: 15/12/18)

Developer: inter6 <inter6@inter6.com>
Repository: https://github.com/inter6/smtp-sender

Release History

v1.2.2
- Custom HELO command
- Add Transmission Delay in EML/SCP panel (Force Single-Thread)
- Bug fix

v1.2.1
- Convert Maven to Gradle
- Bug fix

v1.2.0
- Add Tab Feature (Not compatible v1.1.1 config file)
- UI Adjustment

v1.1.1
- Bug fix

v1.1.0
- Support Source - Remote files by SCP
- Combined EML and EML on Dir Panel

v1.0.1
- Change framework to Spring-Boot (Required Java 7 or later)
- UI Adjustment

v1.0.0
- Official Release
- Bug fix

v0.4.1
- Add Tools - Base64 encoder/decoder
- Add Tools - DNS Query

v0.4.0
- Can change root Content-Type in MIME Editor
- Add Tools - RFC2074 encoder/decoder
- Bug fix

v0.3.2
- Add/Replace Date header
- Bug fix

v0.3.1
- Improve Multi-thread

v0.3.0
- Support Multi-thread
- Display Send Progress Rate

v0.2.2
- Support TLS
- Improve MIME editor

v0.2.0
- Add MIME editor

v0.1.2
- Support SSL
- Support Auth - PLAIN, LOGIN, CRAM-MD5
- Support Source - EML files on directories

v0.1.0
- No auth SMTP send
- Support Source - MIME text, EML files